### ISSUE TITLE
processNotification should be global scope instead of public

### ISSUE THREAD

**Issue by mattr9124** [Adyen/adyen-salesforce-oms#25]
**Is your feature request related to a problem? Please describe.**
Problem is I want to extend the AdyenAsyncAdapter class in order to add some additional checks before processing. This is possible on the processRequest as it is public, although not possible for the processNotification which is declared public.

**Describe the solution you'd like**

Change
```public CommercePayments.GatewayNotificationResponse processNotification```
to 
```global CommercePayments.GatewayNotificationResponse processNotification```

**Describe alternatives you've considered**
My workaround for now is to use a custom webhook listener where I do my preprocessing and then call the notify endpoint from my listener. It works, but could be saved all this trouble if the above method was global and extendable.

**Comment by ShubhamVijaivargiya** [comment]
Hi @mattr9124,

Thank you for raising this enhancement request.

We will discuss your request internally and then decide on an action plan. We encourage you to watch our repo to get an update on when the new release is out.

Thanks
Shubham

**Comment by dcardos** [comment]
The new Release now uses `AdyenGatewayAdapter` class which has global methods.
